# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

when:
  event: push
  branch: master

steps:
  - name: ci-checks
    image: oven/bun:1-alpine
    commands:
      - bun install --frozen-lockfile
      - bun run ci

  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.lan.guillevc.xyz/guille/listseerr
      registry: git.lan.guillevc.xyz
      username:
        from_secret: registry_user
      password:
        from_secret: registry_password
      tags: dev
      build_args:
        - COMMIT_SHA=${CI_COMMIT_SHA}
      labels:
        - org.opencontainers.image.revision=${CI_COMMIT_SHA}
        - org.opencontainers.image.created=${CI_PIPELINE_CREATED}
        - org.opencontainers.image.source=${CI_REPO_LINK}
