when:
  event: push
  branch: master

steps:
  - name: ci-checks
    image: oven/bun:1-alpine
    commands:
      - bun install --frozen-lockfile
      - bun run ci

  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dry_run: true
      tags: listseerr:latest
