# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: ci

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'
      - run: bun install --frozen-lockfile
      - run: bun run ci
